spring.datasource.url=jdbc:postgresql://dpg-d8ajce3bc2fs73835i90-a.oregon-postgres.render.com:5432/hospital_db_k0uc
spring.datasource.username=hospital_db_k0uc_user
spring.datasource.password=E3YTaq5NJyUWyLaFGYUqGvFH6ayJN13L

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}
server.address=0.0.0.0